---
  - name: Provision the etcd Cluster
    file: path={{ item }} state=directory
    with_items:
         -  /etc/etcd/
         - /var/lib/etcd
    tags:
      - controller

  - name: copy certificates in /etc/etcd dir
    copy: src={{ item }} dest=/etc/etcd/
    with_items:
         - /etc/ansible/roles/setting_up_CA_TLS_Cert/files/ca.pem
         - /etc/ansible/roles/setting_up_CA_TLS_Cert/files/kubernetes-key.pem
         - /etc/ansible/roles/setting_up_CA_TLS_Cert/files/kubernetes.pem
    tags:
      - controller
 
  - name: Download the etcd tar package
    get_url:
      url:  https://github.com/coreos/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz
      dest: /root/
      validate_certs: no
    tags:
      - controller

  - name:  unarchive etcd cluster
    unarchive:
      src: /root/etcd-{{ etcd_version }}-linux-amd64.tar.gz
      dest: /root/
      remote_src: yes
    tags:
      - controller

  - name: Install the etcd binaries 
    shell: >
           cp /root/etcd-{{ etcd_version }}-linux-amd64/etcd* /usr/local/bin/
    ignore_errors: yes
    tags:
      - controller

  - name: move it to the systemd system directory
    template:
      src: etcd_service.j2 
      dest: /etc/systemd/system/etcd.service 
    notify:
      - Start the etcd service
    tags:
      - controller 
  - name: restart etcd service
    service: name=etcd state=restarted 
