---
  - name: Restart haproxy service
    service:
      name: haproxy
      state: restarted
      enabled: yes

  - name: Restart keepalived service
    service:
      name: keepalived
      state: restarted
      enabled: yes
