kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: AfJ/OhyKaJX1tOAFO7RcTLM9uSah5yrGHjakeuTYlVw=
      - identity: {}
