---
  - name: create directory on remote machine 
    file: path=/root/.ssh  state=directory
  - name: copy public key in authorized file to remote 
    copy: src=id_rsa.pub dest=/root/.ssh/authorized_keys mode=0600
