---
  - name: copy inventory file on local desk
    copy:
      src: /etc/ansible/hosts
      dest: /tmp/hosts
  - name: create route shell files
    shell: >
           more /tmp/hosts  | grep CIDR | grep -v `hostname` | awk {'print $3 " " $2'}  | sed -e 's/POD_CIDR=/route add -net /g' -e 's/host_ip=/gw /g' > /tmp/routes

  - name: add these roules parmenently 
    shell: >
           sed -i -e '/# By default this script does nothing./r /tmp/routes' /etc/rc.local;
           bash /etc.rc.local
